ALTER TABLE `wechat_red_pack` CHANGE `pm_order_id` `pm_order_id` VARCHAR(30) NOT NULL;
ALTER TABLE `wechat_red_pack` ADD `even_name` VARCHAR(20) NOT NULL AFTER `pm_order_id`, ADD INDEX (`even_name`);
ALTER TABLE `wechat_red_pack` CHANGE `even_name` `even_name` VARCHAR(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '';
ALTER TABLE `wechat_red_pack` ADD `even_key` VARCHAR(20) NOT NULL DEFAULT '' AFTER `even_name`, ADD INDEX (`even_key`);
ALTER TABLE `prepay_lottery_gift` ADD `even_name` VARCHAR(20) NOT NULL DEFAULT '' AFTER `id`, ADD INDEX (`even_name`);
ALTER TABLE `prepay_lottery_gift` ADD `project_id` INT NOT NULL DEFAULT '0' AFTER `even_name`, ADD INDEX (`project_id`);
ALTER TABLE `prepay_lottery_gift` CHANGE `project_id` `project_house_id` INT(11) NOT NULL DEFAULT '0';
ALTER TABLE `prepay_lottery_result` ADD `project_house_id` INT NOT NULL DEFAULT '0' AFTER `id`, ADD INDEX (`project_house_id`);
ALTER TABLE `prepay_lottery_gift` ADD `git_key` INT NOT NULL DEFAULT '0' AFTER `stock`;
ALTER TABLE `prepay_lottery_gift` ADD `icon` VARCHAR(255) NOT NULL DEFAULT '' AFTER `git_key`;
ALTER TABLE `prepay_lottery_result` ADD `even_name` VARCHAR(20) NOT NULL DEFAULT '' AFTER `id`;