CREATE TABLE `house_card` (
`id`  int(11) UNSIGNED NOT NULL AUTO_INCREMENT ,
`region_id`  int(11) UNSIGNED NOT NULL DEFAULT 0 ,
`project_id`  int(11) UNSIGNED NOT NULL DEFAULT 0 ,
`house_id`  int(11) UNSIGNED NOT NULL DEFAULT 0 ,
`card_num`  int(11) UNSIGNED NOT NULL DEFAULT 0 ,
`url_key`  varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' ,
`auth_num`  int(11) UNSIGNED NOT NULL DEFAULT 0 ,
PRIMARY KEY (`id`)
)
ENGINE=InnoDB
DEFAULT CHARACTER SET=utf8mb4 COLLATE=utf8mb4_general_ci
ROW_FORMAT=COMPACT
;

