<?php
/**
 * Created by
 * Author: HQM
 * Time: 2018/11/14
 * Description:
 */

namespace apps\api\controllers;

class PayController extends Controller
{
    public $modelClass = '';

    public function actions()
    {
        $actions = parent::actions(); // TODO: Change the autogenerated stub
        unset($actions['index']);
        unset($actions['delete']);
        unset($actions['update']);
        unset($actions['create']);

        return $actions;
    }

}